<a href="https://colab.research.google.com/github/MachineLearnia/Python-Machine-Learning/blob/master/10%20-%20Numpy%20(les%20Bases).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 10/30 Numpy : Array ndarray

In [1]:
import numpy as np

## 1. **ndarray** Array Generators

* Default generator: **ndarray()**
* 1D generators: **np.linspace** and **np.arange()**
* ND generators: **np.zeros()**, **np.ones()**, **np.random.randn()** (these are the most useful)


In [2]:
A = np.array([1, 2, 3])  # default generator, converts lists (or other objects) into an ndarray
A = np.zeros((2, 3))      # 2x3 array of zeros
B = np.ones((2, 3))       # 2x3 array of ones
C = np.random.randn(2, 3) # random array (normal distribution) with shape 2x3
D = np.random.rand(2, 3)  # random array (uniform distribution)

E = np.random.randint(0, 10, [2, 3])  # array of random integers from 0 to 10 with shape 2x3

In [4]:
A = np.ones((2, 3), dtype=np.float16)  # defines the type and the memory space to occupy
B = np.eye(4, dtype=np.bool)           # creates an identity matrix and converts the elements to bool type

C:\Users\Jonathan Tabet\AppData\Local\Temp\ipykernel_30456\1427681679.py:2: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  B = np.eye(4, dtype=np.bool)           # creates an identity matrix and converts the elements to bool type


In [5]:
A = np.linspace(1,10, 10)
B = np.arange(0, 10, 10)

## 2. Importants Features 
- size
- shape

In [6]:
A = np.zeros((2, 3))  # create an array with shape (2, 3)

print(A.size)   # number of elements in array A
print(A.shape)  # dimensions of array A (as a tuple)

print(type(A.shape))  # proof that shape is a tuple

print(A.shape[0])  # number of elements in the first dimension of A


6
(2, 3)
<class 'tuple'>
2


## 3. Important Methods

* **reshape()**: to resize an array
* **ravel()**: to flatten an array (so it becomes one-dimensional)
* **squeeze()**: removes any dimension equal to 1
* **concatenate()**: joins two arrays along a specified axis (also available as hstack and vstack)


In [10]:
A = np.zeros((2, 3))  # create an array with shape (2, 3)

A = A.reshape((3, 2))  # resize array A (3 rows, 2 columns)
A.ravel()               # flatten array A (single dimension)
A.squeeze()             # remove "1" dimensions from A

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
A = np.zeros((2, 3))  # create an array with shape (2, 3)
B = np.ones((2, 3))   # create an array with shape (2, 3)

np.concatenate((A, B), axis=0)  # axis 0: equivalent to np.vstack((A, B))

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.concatenate((A, B), axis=1)  # axis 1: equivalent to np.hstack((A, B))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

## 4. Exercise and Solutions


In [12]:
def initialization(m, n):
    # m: number of rows
    # n: number of columns
    # returns a random matrix of shape (m, n+1)
    # with a bias column (filled with "1") on the far right

    return X


In [13]:
# SOLUTION
def initialization(m, n):
    # m: number of rows
    # n: number of columns
    # returns a random matrix of shape (m, n+1)
    # with a bias column (filled with "1") on the far right
    X = np.random.randn(m, n)
    X = np.concatenate((X, np.ones((X.shape[0], 1))), axis=1)

    return X

initialization(3, 4)


array([[-0.53272319,  0.86654173,  1.71046729, -1.21838536,  1.        ],
       [ 0.32713364,  0.62399468,  0.59483111, -0.99809618,  1.        ],
       [-1.29757005, -0.34866459, -1.57517622, -0.77032532,  1.        ]])